-- AppTestFramework schema — V1 initial
-- Compatible with H2 (default / embedded) and PostgreSQL (production profile).

CREATE TABLE runs (
    run_id          VARCHAR(36)  PRIMARY KEY,
    apk_file_name   VARCHAR(255),
    state           VARCHAR(20)  NOT NULL,
    device_serial   VARCHAR(100),
    error           TEXT,
    created_at      BIGINT       NOT NULL,
    started_at      BIGINT,
    finished_at     BIGINT,
    categories      TEXT,
    compat_versions VARCHAR(255),
    package_name    VARCHAR(255),
    app_label       VARCHAR(255),
    version_name    VARCHAR(100),
    version_code    BIGINT,
    min_sdk         INTEGER,
    target_sdk      INTEGER,
    apk_size_bytes  BIGINT,
    steps_json      TEXT
);

CREATE INDEX idx_runs_state       ON runs (state);
CREATE INDEX idx_runs_created_at  ON runs (created_at DESC);
CREATE INDEX idx_runs_package     ON runs (package_name);

-- ─────────────────────────────────────────────────────────────────
-- Per-category result within a run
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE test_results (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        VARCHAR(36)  NOT NULL REFERENCES runs (run_id) ON DELETE CASCADE,
    category_key  VARCHAR(100),
    category_name VARCHAR(255),
    status        VARCHAR(20),
    started_at    BIGINT,
    finished_at   BIGINT,
    summary       TEXT
);

CREATE INDEX idx_test_results_run ON test_results (run_id);

-- ─────────────────────────────────────────────────────────────────
-- Individual defect / observation produced by a test category
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE findings (
    finding_id       VARCHAR(36)  PRIMARY KEY,
    result_id        BIGINT       NOT NULL REFERENCES test_results (id) ON DELETE CASCADE,
    severity         VARCHAR(20),
    title            VARCHAR(500),
    detail           TEXT,
    evidence         VARCHAR(500),
    ts_millis        BIGINT,
    occurrence_count INTEGER
);

CREATE INDEX idx_findings_result   ON findings (result_id);
CREATE INDEX idx_findings_severity ON findings (severity);

-- ─────────────────────────────────────────────────────────────────
-- Dashboard user accounts
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255)        NOT NULL,
    role          VARCHAR(50)         NOT NULL DEFAULT 'ADMIN',
    created_at    TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active        BOOLEAN             NOT NULL DEFAULT TRUE
);

-- ─────────────────────────────────────────────────────────────────
-- Module session snapshots (compat / l10n / rc / ads / tc)
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE module_sessions (
    id            VARCHAR(36) PRIMARY KEY,
    module        VARCHAR(20) NOT NULL,
    apk_file_name VARCHAR(255),
    state         VARCHAR(30),
    created_at    BIGINT,
    updated_at    BIGINT,
    data_json     TEXT
);

CREATE INDEX idx_module_sessions_module ON module_sessions (module);
CREATE INDEX idx_module_sessions_updated ON module_sessions (updated_at DESC);
